### ISSUE TITLE
Netty SocketIO thrown Null Pointer Exception.

### ISSUE THREAD

**Issue by throrin19** [tolgee/tolgee-platform#1190]
Hi,

I try to launch tolgee in kubernetes (I create a testing helm chart here : https://github.com/throrin19/helm-tolgee)

But, when I try to launch tolgee, I have this log error and I don't understand why :  

```
2022-06-10 07:53:50.312 INFO 1 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat started on port(s): 8080 (http) with context path ''
--
Fri, Jun 10 2022 09:53:50 | 2022-06-10 07:53:50.356 INFO 1 --- [ main] io.tolgee.Application$Companion : Started Application.Companion in 30.007 seconds (JVM running for 31.248)
Fri, Jun 10 2022 09:53:50 | 2022-06-10 07:53:50.356 INFO 1 --- [ionShutdownHook] i.t.c.SocketIoServerCommandLineRunner : Netty SocketIO thrown Null Pointer Exception.
Fri, Jun 10 2022 09:53:50 | 2022-06-10 07:53:50.445 WARN 1 --- [ionShutdownHook] .s.c.a.CommonAnnotationBeanPostProcessor : Destroy method on bean with name 'postgresEmbeddedRunner' threw an exception: kotlin.UninitializedPropertyAccessException: lateinit property proc has not been initialized
Fri, Jun 10 2022 09:53:50 | 2022-06-10 07:53:50.501 INFO 1 --- [ main] ConditionEvaluationReportLoggingListener :
Fri, Jun 10 2022 09:53:50 |  
Fri, Jun 10 2022 09:53:50 | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
Fri, Jun 10 2022 09:53:50 | 2022-06-10 07:53:50.532 INFO 1 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
Fri, Jun 10 2022 09:53:50 | 2022-06-10 07:53:50.535 INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown initiated...
Fri, Jun 10 2022 09:53:50 | 2022-06-10 07:53:50.543 ERROR 1 --- [ main] o.s.boot.SpringApplication : Application run failed
Fri, Jun 10 2022 09:53:50 |  
Fri, Jun 10 2022 09:53:50 | org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'initialUserCreatorCommandLineRunner': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
Fri, Jun 10 2022 09:53:50 | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220) ~[spring-beans-5.3.19.jar:5.3.19]
Fri, Jun 10 2022 09:53:50 | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.19.jar:5.3.19]
Fri, Jun 10 2022 09:53:50 | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar:5.3.19]
Fri, Jun 10 2022 09:53:50 | at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:671) ~[spring-beans-5.3.19.jar:5.3.19]
Fri, Jun 10 2022 09:53:50 | at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659) ~[spring-beans-5.3.19.jar:5.3.19]
Fri, Jun 10 2022 09:53:50 | at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1300) ~[spring-context-5.3.19.jar:5.3.19]
Fri, Jun 10 2022 09:53:50 | at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:754) ~[spring-boot-2.6.7.jar:2.6.7]
Fri, Jun 10 2022 09:53:50 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-2.6.7.jar:2.6.7]
Fri, Jun 10 2022 09:53:50 | at io.tolgee.Application$Companion.main(Application.kt:29) ~[app/:na]
Fri, Jun 10 2022 09:53:50 | at io.tolgee.Application.main(Application.kt) ~[app/:na]
Fri, Jun 10 2022 09:53:50 |  
Fri, Jun 10 2022 09:53:50 | 2022-06-10 07:53:50.545 INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown completed.
```

The log says to launch application with debug option. I did not see mention of this option in tolgee env variables.

Thanks for your help

Edit : The error seems to be the socker.io server. I try to disable it with the env `tolgee.socket-io.enabled` but I have no change 😞

**Comment by throrin19** [comment]
I find how to activate debug :  

- You should add the env variable `debug=true`

And this is the complete log : https://gist.github.com/throrin19/3d8cf5e76df71a7c1930e6c1a5d62e35

But I can't find any more informations about the problem

**Comment by JanCizmar** [comment]
Hmm. Can you provide also the full log without the debug. I think there will be some problem above.

**Comment by throrin19** [comment]
Thanks for your help @JanCizmar , this is the complete log without debug (I recreate the entire service and you have all database part in it) : https://gist.github.com/throrin19/682692d713018a398c3479fa43f60607

**Comment by JanCizmar** [comment]
It looks like the app is stoped right after it's start. Can you maybe check kubernetes logs? Isn't it evicted or something?

**Comment by JanCizmar** [comment]
Thanks for creating helm chart BTW.

**Comment by throrin19** [comment]
It's normal 😄
