### ISSUE TITLE
[Bug] On Vue 3 TolgeeMixin import : "Cannot read properties of undefined (reading 'tolgee')"

### ISSUE THREAD

**Issue by KaKi87** [tolgee/tolgee-platform#1209]
```js
import { T, TolgeeMixin } from '@tolgee/vue';
const app = createApp({
    extends: App,
    components: { T },
    mixins: [TolgeeMixin]
});
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'tolgee')
    at Proxy.data (@tolgee_vue.js?v=1159c8eb:27318:37)
    at Proxy.mergedDataFn (runtime-core.esm-bundler.js:3676:92)
    at applyOptions (runtime-core.esm-bundler.js:3373:34)
    at finishComponentSetup (runtime-core.esm-bundler.js:7286:9)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7198:9)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at render2 (runtime-core.esm-bundler.js:6209:13)
    at mount (runtime-core.esm-bundler.js:4402:25)
    at app.mount (runtime-dom.esm-bundler.js:1605:23)
    at index.js?t=1656585368274:61:5
```
![Screenshot from 2022-06-30 12-38-31](https://user-images.githubusercontent.com/21284089/176657567-7798768f-af8c-4ce9-a888-e603eff3c20d.png)
Thanks

**Comment by stepan662** [comment]
Hey, this is currently not possible as TolgeeMixin is using TolgeeProvider under the hood and so this way it will fail to find the context in App. You need to use TolgeeMixin only in components wrapped with TolgeeProvider, so you'll need to list it in component setup every time.

You can however register `T` component globally:
```
app.component('T', T);
```
and when you use inside TolgeeProvider it will work fine.

However Mixins are no longer recommended (https://vuejs.org/api/options-composition.html#mixins) as it is better to use composition API, which is supported by Tolgee: https://tolgee.io/docs/web/using_with_vue/translating#imperative-translation.

**Comment by KaKi87** [comment]
But, my *whole* app *is* wrapped under `TolgeeProvider`.

**Comment by stepan662** [comment]
Yep, but if I understand it correctly, this is the app setup and so you are applying the mixin even to 'App' itself, which is not wrapped - wrapping happens inside and therefore it gives you an error. Unfortunately I didn't find a way how to define mixin globally this way.
