### ISSUE TITLE
Users can't change their profile pictures and names

### ISSUE THREAD

**Issue by Schamppu** [tolgee/tolgee-platform#1782]
I have deployed Tolgee on a docker container, but my users can't change their profile pictures or names. When changing profile picture, it just keeps loading. Changing user name says they are missing the permission.

I can add screenshots and texts can be br changed, so the DB seems to work just fine.

Is there anything I can do to fix this issue on my end?

**Comment by JanCizmar** [comment]
Hello! Thanks for the query. Is there any error logged in the console? This seems weird, since these operations are well tested.

**Comment by Schamppu** [comment]
![image](https://github.com/tolgee/tolgee-platform/assets/41271610/2b5d0aad-b44a-4488-8013-6bb50a78d138)

@JanCizmar it throws error 403 while trying it.

**Comment by JanCizmar** [comment]
Well, this is related to your custom setup. I have no idea, why this can happen. This operation works on Tolgee cloud and is tested. You will have to debug this yourself or you can consider using Tolgee cloud or subscribe for business plan for self-hosted instance to get advanced support.

**Comment by Schamppu** [comment]
@JanCizmar I tried debugging this for hours by changing Nginx configurations and reading docker logs.

The issue is related to Spring. Whenever I try to change my username, the Tolgee container prints this error:
```
2023-07-17 13:45:50.839  WARN 1 --- [nio-8000-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class java.util.LinkedHashMap] with preset Content-Type 'application/javascript;charset=UTF-8']     
2023-07-17 13:45:59.609  WARN 1 --- [nio-8000-exec-5] o.s.w.s.s.t.h.DefaultSockJsService       : Origin check enabled but transport 'jsonp' does not support it.
2023-07-17 13:46:03.846 ERROR 1 --- [nio-8000-exec-6] io.tolgee.ExceptionHandlers              : org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class java.util.LinkedHashMap] with preset Content-Type 'text/html;charset=UTF-8'
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:312)
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219)
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
        at org.springframework.hateoas.server.mvc.RepresentationModelProcessorHandlerMethodReturnValueHandler.handleReturnValue(RepresentationModelProcessorHandlerMethodReturnValueHandler.java:108)
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
```

This seems like something that might need resolving on Tolgee's end? I've set the CORS settings properly and **everything else works, except for changing username or profile picture**. On stuff I found online about this specific issue, it seems like it might be caused because of missing getters:
https://stackoverflow.com/questions/33832735/spring-boot-application-no-converter-found-for-return-value-of-type
https://dzone.com/articles/spring-boot-restcontroller-error-no-converter-foun

Or not having certain message converters or something:
https://stackoverflow.com/questions/40755034/no-converter-found-for-return-value-of-type-class-java-util-linkedhashmap

Seems like a weird issue to me, and I'm running out of options how to fix this on my end. And it seems like it isn't something caused by my CORS settings.

**Comment by JanCizmar** [comment]
https://github.com/tolgee/tolgee-platform/pull/1806

**Comment by Schamppu** [comment]
Yeah, I'd like to comment here that it works now perfectly. Thanks!
