### ISSUE TITLE
webui: nodejs v18 errors out with "ERR_OSSL_EVP_UNSUPPORTED" when running "npm run start"

### ISSUE THREAD

**Issue by gabriel-v** [tolgee/tolgee-platform#1941]
When following the steps here: https://github.com/tolgee/tolgee-platform/wiki/Development#running-the-frontend

With nodejs version v18 you get an error similar to this: https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

Full output from my machine: 

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/NormalModule.js:471:10)
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/NormalModule.js:503:5
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/NormalModule.js:358:12
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/work/tolgee-translation/tolgee-platform/webapp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/work/tolgee-translation/tolgee-platform/webapp/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/NormalModule.js:417:16)
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/NormalModule.js:452:10
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/webpack/lib/NormalModule.js:323:13
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/work/tolgee-translation/tolgee-platform/webapp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /work/tolgee-translation/tolgee-platform/webapp/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0

```

The solution is this: 

```
export NODE_OPTIONS=--openssl-legacy-provider
npm run start
```

https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported/69746937#69746937

And with the above env, it works.

You might want to add this fix to the docs.

**Comment by stepan662** [comment]
Hey, what docs have you been following? Just readme? https://github.com/tolgee/tolgee-platform/tree/main/webapp

The issue is the CRA is deprecated. We want to upgrade (to VITE probably), but didn't have time to push it yet.

**Comment by gabriel-v** [comment]
linked at top of ticket - https://github.com/tolgee/tolgee-platform/wiki/Development#running-the-frontend

from this suggeestion -  https://github.com/tolgee/tolgee-platform/issues/1940#issuecomment-1755523502

you might want to reconsolidate the readme and the wiki into a single up-to-date source, through this is always easier said than done

**Comment by stepan662** [comment]
Ah, yeah, forgot we also have wiki 😄 
I'll try to upgrade it to node 18.
